name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Test1
      id: test1
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Test1
        setup-command: ''
        command: python program4.py
        input: "-4"
        expected-output: |-
          Enter a number:
          Error: Factorial is not defined for negative numbers.
        comparison-method: exact
        timeout: 10
        max-score: 10
    - name: Test2
      id: test2
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Test2
        setup-command: ''
        command: python program4.py
        input: '0'
        expected-output: |-
          Enter a number:
          The factorial of 0 is 1
        comparison-method: exact
        timeout: 10
        max-score: 10
    - name: Test3
      id: test3
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Test3
        setup-command: ''
        command: python program4.py
        input: '1'
        expected-output: |-
          Enter a number:
          The factorial of 1 is 1
        comparison-method: exact
        timeout: 10
        max-score: 10
    - name: Test4
      id: test4
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Test4
        setup-command: ''
        command: python program4.py
        input: '5'
        expected-output: |-
          Enter a number:
          The factorial of 5 is 120
        comparison-method: exact
        timeout: 10
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST1_RESULTS: "${{steps.test1.outputs.result}}"
        TEST2_RESULTS: "${{steps.test2.outputs.result}}"
        TEST3_RESULTS: "${{steps.test3.outputs.result}}"
        TEST4_RESULTS: "${{steps.test4.outputs.result}}"
      with:
        runners: test1,test2,test3,test4
